### ISSUE TITLE
22. Rigid spine syndrome -> Central core disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#211] opened 2017-03-21 22:57 UTC
This one is weird to me too, because rigid spine syndrome is shown to be a suggested subclass of orphanet_598 multiminicore myopathy, which is a subclass of Central core disease, but according to the image, there is not a direct subclass relation.

OMIM has RIGID SPINE SYNDROME and MINICORE MYOPATHY, SEVERE CLASSIC FORM as synonyms and Orphanet maps both orphanet_598 multiminicore myopathy and Rigid spine syndrome to the same OMIM term ([602771](https://omim.org/entry/602771))

I think the subclass assertion of Rigid spine syndrome -> orphanet_598 multiminicore myopathy is okay. Is that what I am meant to be looking at though?

![image](https://cloud.githubusercontent.com/assets/6722114/24736305/1420b52c-1a3c-11e7-8f10-b160df0f1b8e.png)

_Updated picture_

**Comment by cmungall** [comment] 2017-03-21 23:30
Yes, in fact there are two new proposed Orphanet subclassOf relationships here. Let's evaluate both.

I'm actually skeptical of both. Starting from the bottom right:

 1. note that Orphanet didn't propose any relationship between RSS and the OMIM, we're inferring equivalence through transitivity. Do we trust that MESH link?
 2. `Orphanet_598 Multiminicore myopathy SubClassOf OMIM_117000 Central Core Disease of Muscle Pr= 0.65` <-- this is coming from an NTBT in Orphanet. Do we believe this?

Overall I'm very skeptical about this configuration. I think we need to look into definitions to see what is correct here

**Comment by cmungall** [comment] 2017-03-22 00:25
Note that DO added a class for rigid spine syndrome 1 a month ago, linked to the OMIM:

http://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_0110633

DO did not choose to make any kind of grouping to multiminocore, contrary to orphanet:

```
 / DOID:4 ! disease
  is_a DOID:7 ! disease of anatomical entity
   is_a DOID:17 ! musculoskeletal system disease
    is_a DOID:0080000 ! muscular disease
     is_a DOID:66 ! muscle tissue disease
      is_a DOID:423 ! myopathy
       is_a DOID:9884 ! muscular dystrophy
        is_a DOID:0050557 ! congenital muscular dystrophy
         is_a DOID:0110633 ! rigid spine muscular dystrophy 1 ***
```

But the DO entry is informative:

```
id: DOID:0110633
name: rigid spine muscular dystrophy 1
namespace: disease_ontology
def: "A congenital muscular dystrophy characterized by intrasarcoplasmic aggregates of desmin resulting in spinal rigidity, abnormal posture (limitation of neck and trunk flexure), progressive scoliosis of the spine, early marked cervico-axial muscle weakness with relatively preserved strength and function of the extremities and progressive respiratory insufficiency that has_material_basis_in homozygous or compound heterozygous mutation in the SEPN1 gene on chromosome 1p36." [url:https://www.ncbi.nlm.nih.gov/pubmed/11528383, url:https://www.ncbi.nlm.nih.gov/pubmed/12192640, url:https://www.ncbi.nlm.nih.gov/pubmed/15122708]
synonym: "Eichsfeld type congenital muscular dystrophy" EXACT []
synonym: "MDRS1" EXACT []
synonym: "RSMD1" EXACT []
synonym: "RSS" EXACT []
synonym: "SEPN1-related myopathy" EXACT []
synonym: "classic MmD" EXACT []
synonym: "classic multiminicore disease" EXACT []
synonym: "classic multiminicore myopathy" EXACT []
synonym: "congenital merosin-positive muscular dystrophy with early spine rigidity" EXACT []
synonym: "desmin-related myopathy with Mallory bodies" EXACT []
synonym: "desmin-related myopathy with Mallory body-like inclusions" EXACT []
synonym: "early-onset desmin-related myopathy" EXACT []
synonym: "rigid spine syndrome" EXACT []
synonym: "severe classic form minicore myopathy" EXACT []
synonym: "severe classic form multicore myopathy" EXACT []
synonym: "severe classic form multiminicore disease" EXACT []
xref: ICD10:G71.2
xref: ICD10:G71.8
xref: MESH:C535683
xref: OMIM:602771
xref: Orphanet:324604
xref: Orphanet:598
xref: Orphanet:84132
xref: Orphanet:97244
is_a: DOID:0050557  ! congenital muscular dystrophy
```

See in particular this reference cited by DO: https://www.ncbi.nlm.nih.gov/pubmed/12192640

This seems the simplest approach, to collapse the classic form into a single node for the form caused by SEPN1. I think some of the Orphanets need collapsing.

I think it should look like this

 * multiminicore disease
    * classic form (SEPN1)
    * atypical form (RYR1)

all under MD?

**Comment by cmungall** [comment] 2017-03-22 00:40
This is what this looks like in the latest kboom run from a few weeks ago:

![img-orphanet_324604](https://cloud.githubusercontent.com/assets/50745/24177097/6aa66d32-0e5d-11e7-9f8f-062a7cdf6af3.png)

it's better, but I think classic and rigid should be merged on orphanet, and the relationship between multiminicore and central core is dubious, shared phenotypes should not be represented with subclassof

**Comment by nicolevasilevsky** [comment] 2017-04-06 03:28
Should I ask Annie about merging classic and rigid spine syndrome? That makes sense to me.

**Closed** 2018-05-09 18:15 UTC
